"""ocjena table

Revision ID: 779df6b4eee2
Revises: 6b99bd2f9b25
Create Date: 2019-08-01 22:07:02.660340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779df6b4eee2'
down_revision = '6b99bd2f9b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocjena', sa.Column('opis', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ocjena', 'opis')
    # ### end Alembic commands ###
